import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { availableTransitions, isTerminal, canManageTicket } from "@/lib/ticket-access";
import { statusLabels, priorityLabels, roleLabels, formatDate } from "@/lib/labels";
import { storageConfigured } from "@/lib/storage";
import TicketActions from "./TicketActions";
export default async function TicketPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await getSession(); if (!session) redirect("/login"); const { id } = await params; if (!z.uuid().safeParse(id).success) notFound();
  const ticket = await db.ticket.findFirst({ where: { id, ...(session.role === "USER" ? { requesterId: session.userId } : {}) }, include: { category: true, requester: { select: { name: true, organization: true, department: true } }, assignee: { select: { name: true } }, attachments: { select: { id: true, originalName: true, size: true } }, messages: { where: session.role === "USER" ? { visibility: "PUBLIC" } : {}, include: { author: { select: { name: true, role: true } } }, orderBy: { createdAt: "asc" } }, statusHistory: { orderBy: { createdAt: "asc" } } } });
  if (!ticket) notFound();
  const technicians = session.role === "ADMIN" ? await db.user.findMany({ where: { isActive: true, role: { in: ["TECHNICIAN", "ADMIN"] } }, select: { id: true, name: true }, orderBy: { name: "asc" } }) : [];
  return <main id="content" className="shell"><Link href="/dashboard">← К заявкам</Link><header className="ticketHeader section"><div><p className="eyebrow">HD-{ticket.number} · {ticket.category.name}</p><h1>{ticket.subject}</h1></div><span className="status">{statusLabels[ticket.status]}</span></header><div className="ticketLayout"><section><article className="card"><h2>Описание</h2><p className="pre">{ticket.description}</p></article><article className="card section"><h2>Переписка</h2>{!ticket.messages.length && <p className="muted">Сообщений пока нет.</p>}{ticket.messages.map(message => <div className={"message " + (message.visibility === "INTERNAL" ? "internal" : "")} key={message.id}><b>{message.author.name}</b><span className="muted"> · {roleLabels[message.author.role]} · {formatDate(message.createdAt)}</span>{message.visibility === "INTERNAL" && <small> · Внутренняя заметка</small>}<p className="pre">{message.body}</p></div>)}<TicketActions id={id} staff={canManageTicket(session.role)} canClaim={canManageTicket(session.role) && ticket.status === "NEW" && !ticket.assigneeId} statuses={availableTransitions(session.role, session.userId, ticket)} currentStatus={ticket.status} finished={isTerminal(ticket.status)} owner={session.userId === ticket.requesterId} technicians={technicians} assigneeId={ticket.assigneeId} uploadsEnabled={storageConfigured()} /></article></section><aside><div className="card"><h2>Детали</h2><p><b>Приоритет:</b> {priorityLabels[ticket.priority]}</p><p><b>Автор:</b> {ticket.requester.name}</p><p><b>Отдел:</b> {ticket.requester.department || "—"}</p><p><b>Организация:</b> {ticket.requester.organization || "—"}</p><p><b>Специалист:</b> {ticket.assignee?.name ?? "Не назначен"}</p><p className="muted">Создана: {formatDate(ticket.createdAt)}</p></div><div className="card section"><h2>Файлы</h2>{!ticket.attachments.length && <p className="muted">Нет файлов</p>}{ticket.attachments.map(file => <p key={file.id}><a href={"/api/attachments/" + file.id}>{file.originalName}</a> <span className="muted">({Math.ceil(file.size / 1024)} КБ)</span></p>)}</div><div className="card section"><h2>История статусов</h2>{ticket.statusHistory.map(history => <p key={history.id} className="muted">{history.fromStatus ? statusLabels[history.fromStatus] : "Создание"} → {statusLabels[history.toStatus]}<br />{formatDate(history.createdAt)}</p>)}</div></aside></div></main>;
}
