"use client";
import { type FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { TicketStatus } from "@prisma/client";
import { statusLabels } from "@/lib/labels";
import { api, errorText } from "@/lib/client-api";
type Props = { id: string; staff: boolean; canClaim: boolean; statuses: TicketStatus[]; currentStatus: TicketStatus; finished: boolean; owner: boolean; technicians: { id: string; name: string }[]; assigneeId: string | null; uploadsEnabled: boolean };
export default function TicketActions({ id, staff, canClaim, statuses, currentStatus, finished, owner, technicians, assigneeId, uploadsEnabled }: Props) {
  const router = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const base = "/api/tickets/" + id;
  async function perform(action: () => Promise<unknown>, reset?: () => void) { setError(""); setBusy(true); try { await action(); reset?.(); router.refresh(); } catch (error) { setError(errorText(error)); } finally { setBusy(false); } }
  function message(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void perform(() => api(base + "/messages", "POST", { body: data.get("body"), visibility: data.get("visibility") ?? "PUBLIC" }), () => form.reset()); }
  function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void perform(() => api(base + "/attachments", "POST", data), () => form.reset()); }
  function assign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void perform(() => api(base + "/assign", "POST", { assigneeId: data.get("assigneeId") })); }
  const actionLabel = (status: TicketStatus) => owner && currentStatus === "RESOLVED" ? status === "CLOSED" ? "Подтвердить решение" : "Вернуть в работу" : status === "IN_PROGRESS" ? "Продолжить работу" : status === "CANCELLED" ? "Отменить заявку" : statusLabels[status];
  return <div className="actions">{finished ? <p role="status" className="muted">Заявка завершена. Переписка и файлы доступны для просмотра.</p> : <><div className="actionRow">{canClaim && <button disabled={busy} onClick={() => perform(() => api(base + "/claim"))}>Взять в работу</button>}{statuses.map(status => <button className="secondary" disabled={busy} key={status} onClick={() => perform(() => api(base + "/status", "POST", { status }))}>{actionLabel(status)}</button>)}</div>{technicians.length > 0 && <form onSubmit={assign} className="inlineForm"><label>Специалист<select name="assigneeId" defaultValue={assigneeId ?? ""} required disabled={busy}><option value="" disabled>Выберите специалиста</option>{technicians.map(tech => <option key={tech.id} value={tech.id}>{tech.name}</option>)}</select></label><button className="secondary" disabled={busy}>Назначить</button></form>}<form onSubmit={message} className="ticketForm section"><label>Сообщение<textarea name="body" required maxLength={10000} rows={4} disabled={busy} /></label>{staff && <label>Видимость<select name="visibility" defaultValue="PUBLIC" disabled={busy}><option value="PUBLIC">Видно пользователю</option><option value="INTERNAL">Только специалистам</option></select></label>}<button disabled={busy}>Отправить сообщение</button></form>{uploadsEnabled && <form onSubmit={upload} className="ticketForm section"><label>Добавить файлы<input name="files" type="file" required multiple disabled={busy} accept="image/png,image/jpeg,image/webp,application/pdf,text/plain" /></label><p className="muted">До 5 файлов за загрузку, каждый до 10 МБ; до 20 файлов в заявке.</p><button className="secondary" disabled={busy}>Загрузить файлы</button></form>}</>}{error && <p role="alert" className="error">{error}</p>}</div>;
}
