import Link from "next/link";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { ticketQuery } from "@/lib/ticket-query";
import { HttpError } from "@/lib/http";
import { statusLabels, priorityLabels, formatDate } from "@/lib/labels";
export default async function Dashboard({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await getSession(); if (!session) redirect("/login");
  let query;
  try { query = ticketQuery(await searchParams, session); } catch (error) { if (!(error instanceof HttpError)) throw error; redirect("/dashboard"); }
  const { filters, where, take, skip } = query;
  const scope = session.role === "USER" ? { requesterId: session.userId } : {};
  const [tickets, total, newCount, progress, waiting] = await Promise.all([
    db.ticket.findMany({ where, include: { category: { select: { name: true } }, assignee: { select: { name: true } } }, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take, skip }), db.ticket.count({ where }),
    db.ticket.count({ where: { ...scope, status: "NEW" } }), db.ticket.count({ where: { ...scope, status: "IN_PROGRESS" } }), db.ticket.count({ where: { ...scope, status: "WAITING_FOR_USER" } }),
  ]);
  const pageLink = (page: number) => "/dashboard?" + new URLSearchParams({ ...Object.fromEntries(Object.entries(filters).map(([key, value]) => [key, String(value)])), page: String(page) });
  return <main id="content" className="shell"><header className="top"><div><p className="eyebrow">IT HELP DESK</p><h1>{session.role === "USER" ? "Мои заявки" : "Очередь поддержки"}</h1></div><Link className="button" href="/tickets/new">+ Новая заявка</Link></header><section className="grid"><div className="card"><b>{newCount}</b><p className="muted">Новые</p></div><div className="card"><b>{progress}</b><p className="muted">В работе</p></div><div className="card"><b>{waiting}</b><p className="muted">Ожидают ответа</p></div></section><form className="filters section" action="/dashboard"><label>Поиск<input name="q" defaultValue={filters.q} maxLength={160} placeholder="Тема или описание" /></label><label>Статус<select name="status" defaultValue={filters.status}><option value="">Все</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Приоритет<select name="priority" defaultValue={filters.priority}><option value="">Все</option>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{session.role !== "USER" && <label>Назначение<select name="assignment" defaultValue={filters.assignment}><option value="">Все</option><option value="mine">Назначены мне</option><option value="unassigned">Без специалиста</option></select></label>}<button>Найти</button><Link href="/dashboard">Сбросить</Link></form><section className="card tableCard"><table><caption className="srOnly">Заявки службы поддержки</caption><thead><tr><th scope="col">№ / Дата</th><th scope="col">Тема</th><th scope="col">Категория</th><th scope="col">Приоритет</th><th scope="col">Статус</th><th scope="col">Специалист</th></tr></thead><tbody>{tickets.map(ticket => <tr key={ticket.id}><td><Link href={"/tickets/" + ticket.id}>HD-{ticket.number}</Link><br /><small className="muted">{formatDate(ticket.createdAt)}</small></td><td><Link href={"/tickets/" + ticket.id}>{ticket.subject}</Link></td><td>{ticket.category.name}</td><td>{priorityLabels[ticket.priority]}</td><td>{statusLabels[ticket.status]}</td><td>{ticket.assignee?.name ?? "Не назначен"}</td></tr>)}</tbody></table>{!tickets.length && <p className="empty muted">Заявок по выбранным условиям нет.</p>}</section><nav className="pagination" aria-label="Страницы заявок">{filters.page > 1 && <Link href={pageLink(filters.page - 1)}>← Назад</Link>}<span>Страница {filters.page} · Найдено: {total}</span>{skip + take < total && <Link href={pageLink(filters.page + 1)}>Далее →</Link>}</nav></main>;
}
